version: 0.9.{build}
image: Visual Studio 2017
configuration: Release

platform: x64

install:
    - choco install make mingw
    - dir c:\tools\mingw64\bin
    - set PATH=c:\tools\mingw64\bin;%PATH%
    - set PATH=/usr/local/bin;%PATH%

build_script:
    - set BUILD_DIR=%cd%
    - echo %BUILD_DIR%
    - cd ..
    - curl -O http://luajit.org/download/LuaJIT-2.0.5.zip
    - unzip LuaJIT-2.0.5.zip
    - cd LuaJIT-2.0.5
    - make install
    - set LUAJIT_LIBRARY=/usr/local/lib/libluajit-5.1.so
    - set LUAJIT_INCLUDE_DIR=/usr/local/include/luajit-2.0
    - cd %BUILD_DIR%
    - cmake .

test: off

# artifacts:
#     - path: x64/Release/myfavoriteproject.exe
#     - name: Release

# deploy:
#     - provider: GitHub
#     - auth_token:
#         - secure: xxxxx
