echo Testing by "Nuthen"

version: 0.9.{build}
image: Visual Studio 2017
configuration: Release

platform: x64

install:
    - choco install make mingw
    - dir c:\tools\mingw64\bin
    - set PATH=c:\tools\mingw64\bin;%PATH%
    - set PATH=/usr/local/bin;%PATH%

build_script:
    - set BUILD_DIR=%cd%
    - echo %BUILD_DIR%
    - cd ..
    - curl -O http://luajit.org/download/LuaJIT-2.0.5.zip
    - unzip LuaJIT-2.0.5.zip
    - cd LuaJIT-2.0.5
    - make install PREFIX=c:/usr
    - dir c:\usr\lib
    - dir c:\usr\lib\lua
    - dir c:\usr\bin\luajit
    - set LUAJIT_DIR=c:\usr\bin/luajit  #c:/projects/LuaJIT-2.0.5
    - set LUAJIT_LIBRARY=c:\usr\bin/luajit
    - cd %BUILD_DIR%
    - cmake .

test: off

# artifacts:
#     - path: x64/Release/myfavoriteproject.exe
#     - name: Release

# deploy:
#     - provider: GitHub
#     - auth_token:
#         - secure: xxxxx
