version: 0.9.{build}
image: Visual Studio 2017
configuration: Release

platform: x64

# install:
#     - choco install make mingw
#     - dir c:\tools\mingw64\bin
#     - set PATH=c:\tools\mingw64\bin;%PATH%
#     - set PATH=/usr/local/bin;%PATH%

build_script:
    - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
    - set BUILD_DIR=%cd%
    - echo %BUILD_DIR%
    - cd ..
    - curl -O http://luajit.org/download/LuaJIT-2.0.5.zip
    - unzip LuaJIT-2.0.5.zip
    - cd LuaJIT-2.0.5\src
    - msvcbuild
    - set LUAJIT_DIR=c:\usr\bin\luajit
    - cd %BUILD_DIR%
    - cmake .

test: off

# artifacts:
#     - path: x64/Release/myfavoriteproject.exe
#     - name: Release

# deploy:
#     - provider: GitHub
#     - auth_token:
#         - secure: xxxxx
