version: 0.9.{build}
image: Visual Studio 2017
configuration: Release

platform: x64

install:
    - choco install make

build_script:
    - set BUILD_DIR=%cd%
    - echo %BUILD_DIR%
    - cd ..
    - curl -O http://luajit.org/download/LuaJIT-2.0.5.zip
    - unzip LuaJIT-2.0.5.zip
    - cd LuaJIT-2.0.5\src
    - make install
    - cd %BUILD_DIR%
    - echo "Building project ..."
    - cmake .

test: off

# artifacts:
#     - path: x64/Release/myfavoriteproject.exe
#     - name: Release

# deploy:
#     - provider: GitHub
#     - auth_token:
#         - secure: xxxxx
